siteaccess:
    groups:
        ezdemo_frontend_group:
            - ezdemo_site
            - ezdemo_site_user
            - eng
            - fre
system:
    ezdemo_frontend_group:
        location_view:
            full:
                edito:
                    template: "BananamanuCacheDemoBundle:full:edito.html.twig"
                    match:
                        Identifier\ContentType: [edito]
                        Id\Location: 130
